/** Versioned vocabulary for selectors exposed by the T3-owned web renderer. */
export const T3_SELECTOR_CONTRACT_VERSION = 1 as const;
export const T3_ROOT_HOOK = "app" as const;

export const T3_SURFACES = [
  "app-shell",
  "portal",
  "overlay",
  "route-chat",
  "route-settings",
  "route-pairing",
  "route-connect",
  "route-auth",
  "route-error",
  "route-appearance-recovery",
  "canvas",
  "title-area",
  "toolbar",
  "sidebar",
  "sidebar-header",
  "thread-list",
  "split-pane",
  "tabs",
  "timeline",
  "timeline-status",
  "composer",
  "composer-body",
  "autocomplete",
  "attachments",
  "composer-banner",
  "settings",
  "settings-nav",
  "settings-panel",
  "command-palette",
  "menu",
  "popover",
  "dialog",
  "tooltip",
  "toast",
  "auth",
  "pairing",
  "profile",
  "update",
  "offline",
  "reconnect",
  "fatal-error",
  "recovery",
  "terminal",
  "terminal-tabs",
  "terminal-resize",
  "terminal-status",
  "terminal-context",
  "files",
  "file-tree",
  "file-preview",
  "code-block",
  "review",
  "diff",
  "diff-header",
  "diff-gutter",
  "diff-hunk",
  "diff-comment",
  "source-control",
  "preview",
  "preview-tabs",
  "preview-toolbar",
  "preview-viewport",
  "preview-loading",
  "preview-progress",
  "preview-recording",
  "preview-annotation",
  "preview-error",
  "provider-badge",
  "model-selector",
  "permission-control",
  "tool-output",
  "native-session",
  "environment",
] as const;

export const T3_PARTS = [
  "thread-row",
  "dialog",
  "drag-region",
  "menu",
  "pairing",
  "popover",
  "reconnect",
  "recovery",
  "terminal-resize",
  "title-area",
  "toast",
  "toolbar",
  "tooltip",
  "timeline-message",
  "timeline-tool-call",
  "timeline-approval",
  "timeline-checkpoint",
  "timeline-status",
  "timeline-markdown",
  "composer-banner",
  "prompt-editor",
  "mode-control",
  "send-button",
  "stop-button",
  "tab",
  "resize-handle",
  "switch",
  "field",
  "slider",
  "diff-gutter",
  "diff-comment",
  "provider-badge",
  "model-selector",
  "permission-control",
  "tool-output",
  "native-session",
  "environment",
  "preview-recording",
  "preview-annotation",
  "preview-loading",
  "markdown",
  "code",
  "heading",
  "label",
  "terminal",
  "composer",
] as const;

export type T3Surface = (typeof T3_SURFACES)[number];
export type T3Part = (typeof T3_PARTS)[number];

export const T3_VISIBLE_STATE_SEMANTICS = [
  "empty",
  "loading",
  "skeleton",
  "error",
  "warning",
  "success",
  "disabled",
  "hover",
  "active",
  "selected",
  "focus-visible",
  "drag",
  "high-contrast",
] as const;

export type T3VisibleState = (typeof T3_VISIBLE_STATE_SEMANTICS)[number];

export type T3StateSemantic =
  | "aria"
  | "data-state"
  | "data-attribute"
  | "native"
  | "pseudo-class"
  | "media";

export type T3StateCoverage = {
  readonly state: T3VisibleState;
  readonly semantic: T3StateSemantic;
  readonly selector: string;
  readonly surfaces: readonly (T3Surface | T3Part)[];
  readonly evidence: string;
  readonly nonApplicable: string;
};

/**
 * Current-artifact state coverage. Surfaces list only states they can render;
 * nonApplicable explains why the state is not a separate hook everywhere else.
 */
export const T3_STATE_COVERAGE = [
  {
    state: "empty",
    semantic: "data-attribute",
    selector: '[data-empty="true"]',
    surfaces: [
      "timeline-status",
      "thread-list",
      "files",
      "file-tree",
      "file-preview",
      "preview-viewport",
      "terminal-status",
    ],
    evidence: "MessagesTimeline/Sidebar/FileBrowser/Preview/ThreadTerminal empty render branches",
    nonApplicable: "Interactive chrome and route roots retain their hook without an empty variant.",
  },
  {
    state: "loading",
    semantic: "aria",
    selector: '[aria-busy="true"]',
    surfaces: [
      "timeline-status",
      "thread-list",
      "files",
      "file-tree",
      "file-preview",
      "preview-loading",
      "preview-progress",
      "terminal-status",
      "reconnect",
      "update",
    ],
    evidence: "Existing aria-busy and preview loading/progress render paths",
    nonApplicable: "Static route/chrome surfaces do not independently load content.",
  },
  {
    state: "skeleton",
    semantic: "data-state",
    selector: '[data-state="skeleton"]',
    surfaces: ["thread-list", "timeline", "files", "file-tree", "file-preview", "settings-panel"],
    evidence: "Existing skeleton data-state selectors in loading collections and panels",
    nonApplicable: "Controls expose loading/disabled semantics instead of skeleton state.",
  },
  {
    state: "error",
    semantic: "aria",
    selector: '[aria-invalid="true"], [role="alert"]',
    surfaces: [
      "route-error",
      "fatal-error",
      "recovery",
      "timeline-status",
      "files",
      "file-preview",
      "preview-error",
      "terminal-status",
      "offline",
      "reconnect",
    ],
    evidence: "Route error, alert, query error, preview failure, and connection error render paths",
    nonApplicable: "Pure navigation and formatting surfaces have no independent error state.",
  },
  {
    state: "warning",
    semantic: "data-attribute",
    selector: '[data-variant="warning"], [data-tone="warning"]',
    surfaces: ["composer-banner", "update", "recovery", "permission-control", "terminal-status"],
    evidence: "Composer banner and status/update warning variants",
    nonApplicable: "Rows and passive chrome use the owning banner/status surface for warnings.",
  },
  {
    state: "success",
    semantic: "data-attribute",
    selector: '[data-variant="success"], [data-tone="success"]',
    surfaces: ["composer-banner", "toast", "update", "reconnect", "permission-control"],
    evidence: "Composer/banner, toast, update, connection, and permission success variants",
    nonApplicable: "Static content surfaces do not announce completion independently.",
  },
  {
    state: "disabled",
    semantic: "native",
    selector: ':disabled, [aria-disabled="true"], [data-disabled]',
    surfaces: [
      "toolbar",
      "thread-list",
      "tabs",
      "tab",
      "composer",
      "prompt-editor",
      "autocomplete",
      "mode-control",
      "send-button",
      "stop-button",
      "settings-nav",
      "settings-panel",
      "menu",
      "popover",
      "dialog",
      "switch",
      "field",
      "slider",
      "preview-recording",
      "permission-control",
      "terminal-tabs",
      "terminal-context",
    ],
    evidence: "Native disabled, aria-disabled, and Base UI data-disabled controls",
    nonApplicable: "Read-only surfaces expose availability through their owning control.",
  },
  {
    state: "hover",
    semantic: "pseudo-class",
    selector: ":hover",
    surfaces: [
      "toolbar",
      "sidebar",
      "thread-list",
      "thread-row",
      "tabs",
      "tab",
      "composer",
      "composer-banner",
      "settings-nav",
      "menu",
      "popover",
      "dialog",
      "tooltip",
      "toast",
      "files",
      "file-tree",
      "preview-toolbar",
      "preview-tabs",
      "terminal-tabs",
      "diff",
      "review",
    ],
    evidence: "Authored :hover and utility state selectors on interactive surfaces",
    nonApplicable: "Noninteractive viewport/status content has no hover contract.",
  },
  {
    state: "active",
    semantic: "aria",
    selector: '[aria-pressed="true"], [data-active="true"], :active',
    surfaces: [
      "toolbar",
      "tabs",
      "tab",
      "composer",
      "mode-control",
      "send-button",
      "settings-nav",
      "menu",
      "popover",
      "preview-tabs",
      "preview-toolbar",
      "terminal-tabs",
      "terminal-context",
      "diff",
    ],
    evidence: "Pressed/active attributes and native :active selectors on controls",
    nonApplicable: "Passive content surfaces have no active interaction state.",
  },
  {
    state: "selected",
    semantic: "aria",
    selector: '[aria-selected="true"], [data-selected]',
    surfaces: [
      "thread-list",
      "thread-row",
      "tabs",
      "tab",
      "settings-nav",
      "menu",
      "popover",
      "preview-tabs",
      "terminal-tabs",
      "files",
      "file-tree",
      "diff",
    ],
    evidence: "Selected tab/thread/menu/file semantics in current renderers",
    nonApplicable:
      "Composer, timeline, and status surfaces delegate selection to controls they contain.",
  },
  {
    state: "focus-visible",
    semantic: "pseudo-class",
    selector: ":focus-visible",
    surfaces: [
      "toolbar",
      "sidebar",
      "thread-list",
      "thread-row",
      "tabs",
      "tab",
      "composer",
      "prompt-editor",
      "autocomplete",
      "settings-nav",
      "settings-panel",
      "menu",
      "popover",
      "dialog",
      "switch",
      "field",
      "slider",
      "terminal-tabs",
      "terminal-context",
      "files",
      "file-tree",
      "preview-toolbar",
      "preview-tabs",
      "preview-recording",
      "diff",
      "review",
    ],
    evidence: "Authored :focus-visible selectors and Base UI focus-visible states",
    nonApplicable: "Passive output and viewport surfaces contain no focusable element.",
  },
  {
    state: "drag",
    semantic: "data-attribute",
    selector: '[data-dragging="true"], [data-dnd-kit-dragging]',
    surfaces: [
      "app-shell",
      "sidebar",
      "thread-list",
      "split-pane",
      "terminal",
      "files",
      "file-tree",
      "preview-viewport",
      "diff",
    ],
    evidence: "Workspace drop, sortable rows, and resize pointer state render paths",
    nonApplicable: "Static text and overlays do not own drag state.",
  },
  {
    state: "high-contrast",
    semantic: "media",
    selector: "@media (forced-colors: active)",
    surfaces: [
      "app-shell",
      "route-chat",
      "route-settings",
      "route-pairing",
      "route-connect",
      "route-auth",
      "route-error",
      "overlay",
      "toolbar",
      "sidebar",
      "tabs",
      "composer",
      "settings",
      "menu",
      "popover",
      "dialog",
      "terminal",
      "files",
      "diff",
      "preview",
    ],
    evidence: "index.css forced-colors media rules and system color keywords",
    nonApplicable: "Remote preview documents and native OS chrome are outside T3 DOM ownership.",
  },
] as const satisfies readonly T3StateCoverage[];

/** Stable hooks are intentionally static; never interpolate content into these values. */
export function t3Surface(surface: T3Surface): { "data-t3-surface": T3Surface } {
  return { "data-t3-surface": surface };
}

export function t3Part(part: T3Part): { "data-t3-part": T3Part } {
  return { "data-t3-part": part };
}
